use serde::Deserialize;
use utoipa::ToSchema;
use validator::Validate;

/// TOTP enable request (first code verification after setup)
#[derive(Debug, Deserialize, Validate, ToSchema)]
pub struct TotpEnableRequest {
    /// 6-digit TOTP code generated by the authenticator app
    #[validate(length(equal = 6, message = "TOTP code must be 6 digits"))]
    pub code: String,
}
